# Generated by Django 3.1.3 on 2022-11-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='chocies',
        ),
    ]
