# Generated by Django 3.1.3 on 2022-11-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_remove_submission_chocies'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinecourseSubmissionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.choice')),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.submission')),
            ],
        ),
    ]
