# Generated by Django 3.1.3 on 2022-11-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_onlinecoursesubmissionchoices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinecoursesubmissionchoices',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='onlinecoursesubmissionchoices',
            old_name='submission_id',
            new_name='submission',
        ),
    ]
