# Generated by Django 3.1.3 on 2022-11-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20221117_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnlinecourseSubmissionChoices',
            new_name='SubmissionChoices',
        ),
    ]
